//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drop_Down.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_saveFormat
    {
        public int id { get; set; }
        public string FormatType { get; set; }
    }
}
